# Generated by Django 3.2.6 on 2021-08-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='snippet',
            field=models.TextField(null=True),
        ),
    ]
