# Generated by Django 3.2.6 on 2021-08-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='image',
            field=models.TextField(default='Some String'),
        ),
        migrations.AddField(
            model_name='mp',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mp',
            name='url',
            field=models.TextField(default='Some String'),
        ),
        migrations.AlterField(
            model_name='mp',
            name='name',
            field=models.CharField(default='Some String', max_length=100),
        ),
    ]
