# Generated by Django 3.2.6 on 2021-08-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mp_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='wiki',
            field=models.TextField(null=True),
        ),
    ]
