# Generated by Django 3.2.6 on 2021-08-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210807_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp',
            name='image',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='mp',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='mp',
            name='rank',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='mp',
            name='url',
            field=models.TextField(default=None),
        ),
    ]
